// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAY4Xe0FYGF9g44A83lAmlTrQ7TA3g01N4',
    appId: '1:828923117741:web:4c865536908eef5fc94624',
    messagingSenderId: '828923117741',
    projectId: 'fyp-project-a0319',
    authDomain: 'fyp-project-a0319.firebaseapp.com',
    storageBucket: 'fyp-project-a0319.firebasestorage.app',
    measurementId: 'G-1PVVBHNJEY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAX0MNKBTMChg5B-kZ1PlTMctb0JdcaXi4',
    appId: '1:828923117741:android:835d63dbfa92ece3c94624',
    messagingSenderId: '828923117741',
    projectId: 'fyp-project-a0319',
    storageBucket: 'fyp-project-a0319.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBE07EIpE3I-JGgsy2c7cXR1MpBGMCIGpg',
    appId: '1:828923117741:ios:cc43d2d8e942670cc94624',
    messagingSenderId: '828923117741',
    projectId: 'fyp-project-a0319',
    storageBucket: 'fyp-project-a0319.firebasestorage.app',
    iosBundleId: 'com.example.smartmediApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBE07EIpE3I-JGgsy2c7cXR1MpBGMCIGpg',
    appId: '1:828923117741:ios:cc43d2d8e942670cc94624',
    messagingSenderId: '828923117741',
    projectId: 'fyp-project-a0319',
    storageBucket: 'fyp-project-a0319.firebasestorage.app',
    iosBundleId: 'com.example.smartmediApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAY4Xe0FYGF9g44A83lAmlTrQ7TA3g01N4',
    appId: '1:828923117741:web:7052b0e4756d72d2c94624',
    messagingSenderId: '828923117741',
    projectId: 'fyp-project-a0319',
    authDomain: 'fyp-project-a0319.firebaseapp.com',
    storageBucket: 'fyp-project-a0319.firebasestorage.app',
    measurementId: 'G-8TEG7PXJ65',
  );
}
